line_length: 120

trailing_whitespace:
  ignores_comments: false

disabled_rules:
  - todo
  - function_parameter_count
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - force_cast
  - identifier_name
  - redundant_string_enum_value
  - large_tuple
  - vertical_parameter_alignment
  - nesting

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
